import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';

const jsonHeaders = { 'Content-Type': 'application/json; charset=utf-8', 'Cache-Control': 'no-store' };
const googleScope = 'https://www.googleapis.com/auth/calendar';
const stateMaxAgeMs = 10 * 60 * 1000;
export function respond(response, status, payload) { for (const [name, value] of Object.entries(jsonHeaders)) response.setHeader(name, value); return response.status(status).json(payload); }
export function config() { const supabaseUrl = (process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL ?? '').replace(/\/$/, ''); return { enabled: process.env.CALENDAR_SCHEDULING_ENABLED === 'true', appUrl: (process.env.PUBLIC_APP_URL ?? '').replace(/\/$/, ''), googleClientId: process.env.GOOGLE_CALENDAR_CLIENT_ID, googleClientSecret: process.env.GOOGLE_CALENDAR_CLIENT_SECRET, stateSecret: process.env.CALENDAR_OAUTH_STATE_SECRET, tokenKey: process.env.CALENDAR_TOKEN_ENCRYPTION_KEY, supabaseUrl, publishableKey: process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY, serviceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY }; }
export function configured(value) { return typeof value === 'string' && value.trim().length > 0; }
export function calendarConfigurationIssue(value) {
  if (!value.enabled) return 'disabled';
  if (![value.appUrl, value.googleClientId, value.googleClientSecret, value.stateSecret, value.tokenKey, value.supabaseUrl, value.publishableKey, value.serviceRoleKey].every(configured)) return 'missing_configuration';
  try { key(value.tokenKey); return null; } catch { return 'invalid_token_encryption_key'; }
}
export function fullyConfigured(value) { return calendarConfigurationIssue(value) === null; }
export function callbackUrl(value) { return `${value.appUrl}/api/calendar/google/callback`; }
export function webhookUrl(value) { return `${value.appUrl}/api/calendar/google/notifications`; }
export function webhookToken(value, connectionId, calendarId) { return createHmac('sha256', value.stateSecret).update(`calendar-webhook:v1:${connectionId}:${calendarId}`).digest('base64url'); }
export async function userFromRequest(request, value) { const authorization = request.headers.authorization; if (!authorization?.startsWith('Bearer ') || !configured(value.supabaseUrl) || !configured(value.publishableKey)) return null; const response = await fetch(`${value.supabaseUrl}/auth/v1/user`, { headers: { apikey: value.publishableKey, Authorization: authorization } }); if (!response.ok) return null; const user = await response.json().catch(() => null); return typeof user?.id === 'string' ? { user, authorization } : null; }
export async function userRpc(value, authorization, name, body) { const response = await fetch(`${value.supabaseUrl}/rest/v1/rpc/${name}`, { method: 'POST', headers: { ...jsonHeaders, apikey: value.publishableKey, Authorization: authorization }, body: JSON.stringify(body) }); return { ok: response.ok, status: response.status, payload: await response.json().catch(() => null) }; }
export async function service(value, path, init = {}) { const response = await fetch(`${value.supabaseUrl}/rest/v1/${path}`, { ...init, headers: { ...jsonHeaders, apikey: value.serviceRoleKey, Authorization: `Bearer ${value.serviceRoleKey}`, ...(init.headers ?? {}) } }); return { ok: response.ok, status: response.status, payload: await response.json().catch(() => null) }; }
function key(value) { const bytes = Buffer.from(value, 'base64'); if (bytes.length !== 32) throw new Error('CALENDAR_TOKEN_ENCRYPTION_KEY must be a base64-encoded 32-byte key.'); return bytes; }
export function encrypt(value, token) { const iv = randomBytes(12); const cipher = createCipheriv('aes-256-gcm', key(value.tokenKey), iv); const ciphertext = Buffer.concat([cipher.update(token, 'utf8'), cipher.final()]); return `v1.${iv.toString('base64url')}.${ciphertext.toString('base64url')}.${cipher.getAuthTag().toString('base64url')}`; }
export function decrypt(value, encrypted) { const [version, ivValue, ciphertextValue, tagValue] = String(encrypted).split('.'); if (version !== 'v1' || !ivValue || !ciphertextValue || !tagValue) throw new Error('Stored calendar credential is invalid.'); const decipher = createDecipheriv('aes-256-gcm', key(value.tokenKey), Buffer.from(ivValue, 'base64url')); decipher.setAuthTag(Buffer.from(tagValue, 'base64url')); return Buffer.concat([decipher.update(Buffer.from(ciphertextValue, 'base64url')), decipher.final()]).toString('utf8'); }
export function createState(value, userId) { const payload = Buffer.from(JSON.stringify({ userId, expiresAt: Date.now() + stateMaxAgeMs, nonce: randomBytes(16).toString('base64url') })).toString('base64url'); return `${payload}.${createHmac('sha256', value.stateSecret).update(payload).digest('base64url')}`; }
export function readState(value, state) { const [payload, signature] = String(state ?? '').split('.'); const expected = createHmac('sha256', value.stateSecret).update(payload ?? '').digest('base64url'); const received = Buffer.from(signature ?? ''); const signed = Buffer.from(expected); if (!payload || !signature || received.length !== signed.length || !timingSafeEqual(received, signed)) return null; try { const data = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')); return typeof data?.userId === 'string' && Number.isFinite(data?.expiresAt) && data.expiresAt > Date.now() ? data : null; } catch { return null; } }
export function googleAuthorizationUrl(value, state) { const url = new URL('https://accounts.google.com/o/oauth2/v2/auth'); url.searchParams.set('client_id', value.googleClientId); url.searchParams.set('redirect_uri', callbackUrl(value)); url.searchParams.set('response_type', 'code'); url.searchParams.set('scope', googleScope); url.searchParams.set('access_type', 'offline'); url.searchParams.set('include_granted_scopes', 'true'); url.searchParams.set('prompt', 'consent'); url.searchParams.set('state', state); return url.toString(); }
export async function refreshGoogleAccessToken(value, refreshToken) { const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: value.googleClientId, client_secret: value.googleClientSecret, refresh_token: refreshToken, grant_type: 'refresh_token' }) }); const payload = await response.json().catch(() => null); if (!response.ok || typeof payload?.access_token !== 'string') throw new Error(payload?.error === 'invalid_grant' ? 'reauthorization_required' : 'provider_unavailable'); return payload.access_token; }
export async function google(value, accessToken, path, init = {}) { const response = await fetch(`https://www.googleapis.com/calendar/v3/${path}`, { ...init, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${accessToken}`, ...(init.headers ?? {}) } }); return { ok: response.ok, status: response.status, payload: await response.json().catch(() => null) }; }
