import { Contact } from './types';

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'cnt-1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@nithyananda.org',
    phoneNumber: '+1 (555) 234-5678',
    owner: 'No owner',
    lifecycleStage: 'Lead',
    leadStatus: 'New',
    priority: 'high',
    lastActivityDate: '2026-08-29 5:58 AM EDT',
    createDate: '2026-08-15',
    company: 'Nithyananda University',
    gender: 'Male',
    avatarBg: '#00a4bd',
    statusBanner: 'Contact has bounced.',
    bounced: true,
    activities: [
      {
        id: 'act-1',
        type: 'email',
        title: 'Email bounced',
        content: 'System notification: Message to rahul.sharma@nithyananda.org returned status 550 (User mailbox unavailable).',
        createdAt: '2026-08-29 05:58 AM EDT',
        author: 'System',
      },
      {
        id: 'act-2',
        type: 'note',
        title: 'Initial Inquiry Note',
        content: 'Requested info regarding Nithyananda University online programs and course enrollment details.',
        createdAt: '2026-08-28 02:15 PM EDT',
        author: 'Support Agent',
      },
    ],
    notes: 'Contact expressed interest in executive programs.',
  },
  {
    id: 'cnt-2',
    name: 'Grace Hopper',
    email: 'grace.hopper@navy.gov',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Marketing Qualified Lead',
    leadStatus: 'Open',
    priority: 'medium',
    lastActivityDate: '2026-08-28 11:30 AM EDT',
    createDate: '2026-08-14',
    company: 'Computing Institute',
    gender: 'Female',
    avatarBg: '#10b981',
    bounced: false,
    activities: [
      {
        id: 'act-3',
        type: 'call',
        title: 'Discovery Call',
        content: 'Discussed compiler architecture requirements and curriculum integration.',
        createdAt: '2026-08-28 11:30 AM EDT',
        author: 'Admissions Lead',
      },
    ],
  },
  {
    id: 'cnt-3',
    name: 'John Doe',
    email: 'john.doe@techcorp.io',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Sales Qualified Lead',
    leadStatus: 'In Progress',
    priority: 'medium',
    lastActivityDate: '2026-08-27 04:20 PM EDT',
    createDate: '2026-08-10',
    company: 'TechCorp Global',
    gender: 'Male',
    avatarBg: '#6366f1',
  },
  {
    id: 'cnt-4',
    name: 'Neha Patel',
    email: 'neha.patel@globaledu.org',
    phoneNumber: '+1 (555) 876-5432',
    owner: 'No owner',
    lifecycleStage: 'Opportunity',
    leadStatus: 'Open Deal',
    priority: 'high',
    lastActivityDate: '2026-08-26 09:15 AM EDT',
    createDate: '2026-08-08',
    company: 'Global Education Alliance',
    gender: 'Female',
    avatarBg: '#f59e0b',
  },
  {
    id: 'cnt-5',
    name: 'Sam Wilson',
    email: 'sam.wilson@brightmind.com',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Lead',
    leadStatus: 'New',
    priority: 'low',
    lastActivityDate: '2026-08-25 01:45 PM EDT',
    createDate: '2026-08-05',
    company: 'BrightMind Labs',
    avatarBg: '#ec4899',
  },
  {
    id: 'cnt-6',
    name: 'Anita Roy',
    email: 'anita.roy@enterprise.com',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Customer',
    leadStatus: 'Connected',
    priority: 'high',
    lastActivityDate: '2026-08-24 03:00 PM EDT',
    createDate: '2026-08-01',
    company: 'Enterprise Corp',
    avatarBg: '#8b5cf6',
  },
  {
    id: 'cnt-7',
    name: 'Suresh Kumar',
    email: 'suresh.kumar@apex.in',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Lead',
    leadStatus: 'Attempted to Contact',
    priority: 'medium',
    lastActivityDate: '2026-08-22 10:00 AM EDT',
    createDate: '2026-07-28',
    company: 'Apex Solutions',
    avatarBg: '#14b8a6',
  },
  {
    id: 'cnt-8',
    name: 'Robert Vance',
    email: 'robert.vance@vanceref.com',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Subscriber',
    leadStatus: 'New',
    priority: 'low',
    lastActivityDate: '2026-08-20 02:22 PM EDT',
    createDate: '2026-07-25',
    company: 'Vance Refrigeration',
    avatarBg: '#0284c7',
  },
  {
    id: 'cnt-9',
    name: 'Bina Shah',
    email: 'bina.shah@innovate.co',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Marketing Qualified Lead',
    leadStatus: 'Open',
    priority: 'medium',
    lastActivityDate: '2026-08-18 05:10 PM EDT',
    createDate: '2026-07-20',
    company: 'Innovate Co',
    avatarBg: '#d97706',
  },
  {
    id: 'cnt-10',
    name: 'Rajesh Ram',
    email: 'rajesh.ram@spiritualfoundation.org',
    phoneNumber: '--',
    owner: 'No owner',
    lifecycleStage: 'Evangelist',
    leadStatus: 'Connected',
    priority: 'high',
    lastActivityDate: '2026-08-15 11:11 AM EDT',
    createDate: '2026-07-15',
    company: 'Nithyananda University',
    avatarBg: '#059669',
  },
];
